### ISSUE TITLE
Printing values with BOOST_UT_FORWARD does not work

### ISSUE THREAD

**Issue by le-migou** [boost-ext/ut#345]
Printing values when a test fails doesn't seem to work with `BOOST_UT_FORWARD`.
Given the two files:
`a.cpp`:
```cpp
#define BOOST_UT_IMPLEMENTATION
#include <boost/ut.hpp>
int main () {}
```
and `b.cpp`
```cpp
#define BOOST_UT_FORWARD
#include <boost/ut.hpp>
using namespace boost::ut;
suite b = []
{
    expect (that % 1 == 2);
};
```
and the command line
```sh
g++ -std=c++2a  -o a a.cpp b.cpp && ./a
```
I get
```
  b.cpp:8:FAILED [false]
===============================================================================
tests:   0 | 0 failed
asserts: 1 | 0 passed | 1 failed
```
The values of the test are not printed. Move the test into `a.cpp` (or put some tests into this file) and the values are printed. E.g. replace `a.cpp` above with
```cpp
#define BOOST_UT_IMPLEMENTATION
#include <boost/ut.hpp>
    using namespace boost::ut;
suite a = []
{
    expect (that % 1 == 2);
};
int main () {}
```
and the result is
```
  a.cpp:6:FAILED [1 == 2]
  b.cpp:6:FAILED [1 == 2]
===============================================================================
tests:   0 | 0 failed
asserts: 2 | 0 passed | 2 failed
```
i.e. both tests print their values.

**Comment by krzysztof-jusiak** [comment]
Not applicable anymore as BOOST_UT_FORWARD/BOOST_UT_IMPLEMENTATION got removed due to not giving enough benefits and having downsides (not portable, no fully functional)
* https://github.com/boost-ext/ut/pull/385
