### ISSUE TITLE
Any syntactic support for conditional assertions?

### ISSUE THREAD

**Issue by kamrann** [boost-ext/ut#371]
Is there anything in place to allow me to do
`expect( x.has_value() and that % x.value() == 10 );`
in such a way that if the first part fails, the second isn't evaluated?

**Comment by krzysztof-jusiak** [comment]
Just working on refinement but it can be done already, although it will change as it's not great ATM :disappointed: 

Currently
```
expect(!expect(x.has_value) and that % x.value() == 10);
```

to be
```
expect(that % x.has_value [fatal] and x.value() == 10); 
```

or with terse syntax
```
x.has_value != null [fatal] and x.value() == 10_i;
```

**Comment by kamrann** [comment]
Great, thank you! Really like the framework so far. 👍

**Comment by kamrann** [comment]
I tried the first approach above, but it still appears to execute the second part even when the first part fails.

Furthermore, I'm not sure I conveyed properly what I was after. In my example, if `x.has_value()` evaluates to `false`, I'd like the `expect` to immediately fail without evaluating `x.value() == 10`, but for any subsequent assertions and tests to proceed. So it's not fatal so much as just a requirement for checking what follows the `and`.

**Comment by krzysztof-jusiak** [comment]
Still working on it https://github.com/boost-ext/ut/pull/372 but it will be something like the following

```
expect(x.has_value() >> fatal and that % x.value() == 10 );
```

or with terse syntax
```
x.has_value() >> fatal and x.value() == 10_i;
```

or with expect
```
expect(x.has_value() >> fatal);
expect(that % x.value() == 10);
```

**Comment by krzysztof-jusiak** [comment]
Fixed by https://github.com/boost-ext/ut/pull/372
