### ISSUE TITLE
Can't link the parallel runner with multiple translation units

### ISSUE THREAD

**Issue by sakhnik** [boost-ext/ut#402]
## Expected Behavior

I'd like to configure a parallel runner for a multi-translation unit program. Just took the example `parallel_runner.cpp`, fit into my `main.cpp` and expected the project to just build.

## Actual Behavior

Tons of linker errors

## Steps to Reproduce the Problem

  1. Take `parallel_runner.cpp`
  2. Create another `test.cpp` with tests
  3. Compile and try to link them together
  4. Observe the messages like the following:
```
[build] : && /usr/bin/c++ -g  CMakeFiles/aoc.dir/main.cpp.o CMakeFiles/aoc.dir/test2.cpp.o -o aoc  -lpthread  -lssl  -lcrypto  -lgmp  -ltbb && :
[build] /usr/bin/ld: /usr/bin/ld: DWARF error: could not find variable specification at offset befe
[build] CMakeFiles/aoc.dir/test2.cpp.o:(.bss._ZN5boost3ext2ut6v1_1_83cfgINS2_8overrideEJEEE[_ZN5boost3ext2ut6v1_1_83cfgINS2_8overrideEJEEE]+0x0): multiple definition of `boost::ext::ut::v1_1_8::cfg<boost::ext::ut::v1_1_8::override>'; /usr/bin/ld: DWARF error: could not find variable specification at offset c578
[build] CMakeFiles/aoc.dir/main.cpp.o:(.bss+0x0): first defined here
[build] collect2: error: ld returned 1 exit status
```

## Specifications

  - Version: v1.1.8
  - Platform: Arch Linux x64
  - Subsystem:

**Comment by krzysztof-jusiak** [comment]
Thanks, @sakhnik. I think the simplest solution will be just to mark `ut::cfg` inline to avoid multiple definitions.

I added a PR which is doing the above for examples:
* https://github.com/boost-ext/ut/pull/404

There is also an integration test in:
* https://github.com/boost-ext/ut/tree/master/test/ft

**Comment by sakhnik** [comment]
Thanks, great work!
