### ISSUE TITLE
Missing coverage data

### ISSUE THREAD

**Issue by VincentBerthier** [boost-ext/ut#403]
## Expected Behavior
The tests should allow the extraction of coverage data.

## Actual Behavior
That's not the case.
Coverage data is extracted from the rest of the program (so it's not a problem of options) but not from anything that runs within the tests. It worked just fine with doctest too but nothing with UT.
The gcno / gcda files are found just fine by lcov, it captures everything that ran outside of UT, but nothing from inside (either from a suite or not).
Maybe an option I missed somewhere?

## Steps to Reproduce the Problem
Not sure, it fails every time on my system and I haven't done anything particularly strange.
I'm using exclusively the BDD but tests made outside of BDD don't show up either.

## Specifications

  - Version: 2020/12/11 (commit 572f1803eb37e7426f683a274e98db27e215cc6a)
  - Platform: Linux
  - Subsystem: Arch
With gcc g++ (GCC) 11.0.0 20201016 (experimental) [devel/c++-modules ea1205e3bbe??M:20201020-1848], c++20 activated.

**Comment by VincentBerthier** [comment]
Alright, uh…
*Cough*
Nevermind, I'm just a moron who messed up his build system's configuration…

Everything's working sorry, I'm closing this.

**Comment by krzysztof-jusiak** [comment]
Thanks, @VincentBerthier. I've taken a look but I just couldn't put my finger on how to approach this issue :thinking: Happy you have figured it out, though :+1:
