### ISSUE TITLE
Conan Center

### ISSUE THREAD

**Issue by jwillikers** [boost-ext/ut#408]
What do you think about making a [Boost-ext].UT package available in [ConanCenter](https://conan.io/center/)?
I would like to able to handle the dependency through Conan, and having it available in ConanCenter seems the easiest way to do so.

Their instructions for doing so are available [here](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md).
I found an example recipe for a header-only library on ConanCenter [here](https://github.com/conan-io/conan-center-index/blob/7a34d7b321de8455b1697c803a38086b208674e5/recipes/picojson/all/conanfile.py).

**Comment by krzysztof-jusiak** [comment]
:+1: :point_up:

**Comment by justend29** [comment]
I was just looking for it on the conan center. This would be great

**Comment by krzysztof-jusiak** [comment]
Agree :point_up: Unfortunately, I have no experience with conan center :disappointed: @jwillikers any ideas on how to start with it?

**Comment by justend29** [comment]
From the documentation I read a week or two ago, which happens to be the exact link @jwillikers linked above, it seems like it's as simple as:
1. requesting access to the 'Early Access Program' on behalf of boost-ext
2. cloning the conan-center-index
3. adding the libraries in a directory with the accepted folder structure they describe
4. making a PR back to the main repo

It seems like the difficult part would be to optimally structure the various libraries under boost-ext into that directory from step 3 such that the various libraries can be easily consumed. For example, the boost library from the conan-center is consumed as one large library that provides CMake components to each major boost component. As a note, though the components aren't very granular, and there seems to be an effort to modularize boost into its components.

It appears that each library under boost-ext already has a single conanfile.py, so maybe there's already been an effort to provide the libraries individually.

**Comment by jwillikers** [comment]
@justend29 I think we can just be concerned with providing [Boost-ext].µt standalone, and doing that would simplify this quite a bit.

I'll go ahead and plan on adding a µt package to conan-center-index when I get time, hopefully within the next couple of weeks. It should be pretty straightforward to copy an existing header-only package and use that as a template for µt.

**Comment by jwillikers** [comment]
PR now open: conan-io/conan-center-index#3997

**Comment by krzysztof-jusiak** [comment]
Awesome! Thank you @jwillikers :clap:

**Comment by jd6060** [comment]
Tremendous!

**Comment by jwillikers** [comment]
Merged!

The package is `boost-ext-ut` and can be found on Conan's website [here](https://conan.io/center/boost-ext-ut).

Include the following in your Conanfile to incorporate µt in your project.

`boost-ext-ut/1.1.8`

We should update the README's Conan section with this information.
The Conan package provides the expected CMake functionality for `find_package`, i.e. the following will work.

```cmake
find_package(ut)

add_executable(my_test my_test.cpp)

target_link_libraries(my_test PRIVATE boost::ut)
```

**Comment by krzysztof-jusiak** [comment]
Awesome, thank you @jwillikers :pray: Great job :clap:

**Comment by krzysztof-jusiak** [comment]
is there a conan badge we can use in README?

**Comment by jwillikers** [comment]
I can't seem to find any.
