### ISSUE TITLE
Document if mut is UB

### ISSUE THREAD

**Issue by libboze** [boost-ext/ut#422]
I am not a language lawyer, but I think it would be nice if mut was documented in a sense that if it is technically UB(as used in examples in tutorial), but it works in practice then that is is mentioned (in docs or code comments). 

cppref says this:

> const_cast makes it possible to form a reference or pointer to non-const type that is actually referring to a const object or a reference or pointer to non-volatile type that is actually referring to a volatile object. Modifying a const object through a non-const access path and referring to a volatile object through a non-volatile glvalue results in undefined behavior. 

Apologies in advance if I misunderstood the cppref quote.

**Comment by JohelEGP** [comment]
It isn't UB as used in the examples. That said, `mut` is much too powerful. I would stick to specifying the lambda as `mutable` if all you need is to modify a lambda's capture for a test (as opposed to non-testing uses, as `mutable` affects all captures, which might have unintended consequences. See https://wg21.link/P2034).

**Comment by libboze** [comment]
Apologies, this is all very weird to me, but you are right, I always assumed that writing to any const object is UB, unless it was a const ref to something that was originally mutable. 

Feel free to close this issue.

**Comment by libboze** [comment]
In fact I will close it, since I presume this is resolve. :)
