### ISSUE TITLE
Recent CMake changes in this project have broken builds of dependent projects

### ISSUE THREAD

**Issue by claremacrae** [boost-ext/ut#430]
### 1. `boost.ut` target seems to no longer be created

That the target `boost.ut` is still provided, to link against, when this project is obtained via add_subdirectory(), FetchContent() or similar...

### 2. include file no longer found: `#include <boost/ut.hpp>`

Example code - this is how I obtain the boost.ut project - UtVersion is master:

https://github.com/claremacrae/ApprovalTests.cpp.CMakeSamples/blob/main/dev_approvals_fetch_content/CMakeLists.txt#L130-L133

```cmake
FetchContent_Declare(boost.ut
        GIT_REPOSITORY https://github.com/boost-ext/ut.git
        GIT_TAG ${UtVersion})
FetchContent_MakeAvailable(boost.ut)
```

The repo goes on to use the target `boost.ut`.

This directory and GitHub action exists to help the ApprovalTests.cpp project have early detection of any changes in test frameworks that might affect our users, when we do our next release.

This has been working for some months, and was still working on the 24th of Feb.

## Actual Behavior

The next build, on 27th Feb at 01:10 GMT gave these errors

### 1.  in clang builds:

```
Fetching boost.ut...
CMake Error at CMakeLists.txt:137 (target_compile_options):
  Cannot specify compile options for target "boost.ut" which is not built by
  this project.
```

### 2. in gcc builds:

```
Building CXX object approvaltests.cpp_build/tests/UT_Tests/CMakeFiles/UT_Tests.dir/UTApprovalTestTests.cpp.o
In file included from /home/runner/work/ApprovalTests.cpp.CMakeSamples/ApprovalTests.cpp.CMakeSamples/ApprovalTests.cpp/ApprovalTests/ApprovalTests.hpp:68,
                 from /home/runner/work/ApprovalTests.cpp.CMakeSamples/ApprovalTests.cpp.CMakeSamples/ApprovalTests.cpp/tests/UT_Tests/UTApprovalTestTests.cpp:3:
/home/runner/work/ApprovalTests.cpp.CMakeSamples/ApprovalTests.cpp.CMakeSamples/ApprovalTests.cpp/ApprovalTests/../ApprovalTests/integrations/ut/UTApprovals.h:14:10: fatal error: boost/ut.hpp: No such file or directory
   14 | #include <boost/ut.hpp>
      |          ^~~~~~~~~~~~~~
compilation terminated.
approvaltests.cpp_build/tests/UT_Tests/CMakeFiles/UT_Tests.dir/build.make:81: recipe for target 'approvaltests.cpp_build/tests/UT_Tests/CMakeFiles/UT_Tests.dir/UTApprovalTestTests.cpp.o' failed
```

## Steps to Reproduce the Problem

**Run this on a unix box with a recent version of either linux or gcc installed:**  

```bash
git clone https://github.com/claremacrae/ApprovalTests.cpp.CMakeSamples
cd ApprovalTests.cpp.CMakeSamples
git clone https://github.com/approvals/ApprovalTests.cpp.git
cd dev_approvals_fetch_content
./build.sh
```

Wait until all the dependencies have been cloned, and then one of the errors will occur - depending on whether you are using gcc or clang.

## Specifications

The failure was detected in a GitHub Actions build. The failing builds can be seen here:

https://github.com/claremacrae/ApprovalTests.cpp.CMakeSamples/actions/runs/604457152

- Linux Clang 6, 8, 9, and 10
- Linux gcc 9 and 10
- macOS Xcode 10.3, 11.7 and 12.

It's likely that the ones that passed are skipping the building of boost.ut

**Comment by ClausKlein** [comment]
That is caused by my changes, I have noted to it during review!

the project name was changed to `ut`.
the imported target to `Boost::ut`

see https://github.com/boost-ext/ut/blob/1cc75c234d4005031cee581102a4a6c8b680df0a/CMakeLists.txt#L134

**Comment by ClausKlein** [comment]
> And those of us that maintain libraries that provide interfaces to this project now have to decide whether to drop supporting the older versions, or not support newer versions....
> 
> Please consider maintaining aliases for backwards compatibility, to prevent this breaking change.

one problem was: the `config version.cmake` file were not installed.
so the `find-package(...)` does not realy work!

and other `Boost` components are all exported as i.e. `Boost::filesystem`

Is it possible to do `add_library(boost.ut ALIAS Boost::ut)` after `FetchContent_MakeAvailable`()?

**Comment by claremacrae** [comment]
> and other `Boost` components are all exported as i.e. `Boost::filesystem`

That's a really interesting point... 

I really agree with the name chosen for this project in Conan-center-index, which is boost-ext-ut - the reason I agree is that this project isn't part of boost, and calling its target Boost.ut creates a cause for confusion, I feel... The name boost-ext-ut feels fairer - suggesting external.

https://github.com/conan-io/conan-center-index/tree/master/recipes/boost-ext-ut

> Is it possible to do `add_library(boost.ut ALIAS Boost::ut)` after `FetchContent_MakeAvailable`()?

I think it's not that simple... it would have to be something like this pseudo-code:

```
if target Boost::ut exists 
    add_library(boost.ut ALIAS Boost::ut)
endif
```

Why impose that on users, and more importantly, the time taken to research the problem when they get the failure, as happened to me today - when it could be a one-liner inside the project?

**Comment by ClausKlein** [comment]
you should be happy, it works now without your config hacks:
```diff
bash-3.2$ git diff
diff --git a/dev_approvals_fetch_content/CMakeLists.txt b/dev_approvals_fetch_content/CMakeLists.txt
index 8e2eaa9..bf562b8 100644
--- a/dev_approvals_fetch_content/CMakeLists.txt
+++ b/dev_approvals_fetch_content/CMakeLists.txt
@@ -132,14 +132,16 @@ FetchContent_Declare(boost.ut
         GIT_TAG ${UtVersion})
 FetchContent_MakeAvailable(boost.ut)
 
-if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
-    # Turn off some checks off for boost.ut
-    target_compile_options(boost.ut INTERFACE
-            -Wno-c99-extensions # Needed for Boost.ut, at least in v1.1.6
-            -Wno-documentation-unknown-command # unknown command tag name \userguide
-            -Wno-weak-vtables
-            -Wno-comma # See https://github.com/boost-ext/ut/issues/398
-            )
+if(TARGET boost.ut)
+    if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
+        # Turn off some checks off for boost.ut
+        target_compile_options(boost.ut INTERFACE
+                -Wno-c99-extensions # Needed for Boost.ut, at least in v1.1.6
+                -Wno-documentation-unknown-command # unknown command tag name \userguide
+                -Wno-weak-vtables
+                -Wno-comma # See https://github.com/boost-ext/ut/issues/398
+                )
+    endif()
 endif()
 
 # -------------------------------------------------------------------
bash-3.2$ 
```

**Comment by ClausKlein** [comment]
@claremacrae one note: IMHO the `fetchcontents` is **very slow** and not very flexible to use.

would it be an option to try https://github.com/cpm-cmake/CPM.cmake

with `local cache enable`, it is really fast!

**Comment by claremacrae** [comment]
> you should be happy, it works now without your config hacks:

....

Thanks - I appreciate the suggestion....

One of the benefits of this project is for me to test out code against multiple different versions of Boost.ut, when we get bug reports from ApprovalTests users, such as https://github.com/approvals/ApprovalTests.cpp/issues/157

Hence my desire to be able to keep building against a variety of Boost.ut versions...

**Comment by claremacrae** [comment]
> @claremacrae one note: IMHO the `fetchcontents` is **very slow** and not very flexible to use.
> 
> would it be an option to try https://github.com/cpm-cmake/CPM.cmake
> 
> with `local cache enable`, it is really fast!

Thanks for that suggestion too...

Another of the benefits - in fact purposes - of ApprovalTests.cpp.CMakeSamples is to provide tested CMake code that we cab embed in to the ApprovalTests.cpp docs, at these two pages:

* https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/CMakeIntegration.md
* https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/ConanIntegration.md

What I'm after is simple, standard things that work with CMake out of the box - and Conan out of the box - so that I can give new users at least one simple thing to try for them...

So there's advantage to me in having a layer on top to speed things up, as it one more thing to document and test....

For that kind of documentation, simpler is better...

**Comment by ClausKlein** [comment]
Fine, I like this: https://github.com/approvals/ApprovalTests.cpp/blob/master/CMake/WarningsAsErrors.cmake

**Comment by claremacrae** [comment]
> Is it possible to do `add_library(boost.ut ALIAS Boost::ut)` after `FetchContent_MakeAvailable`()?

Just to help anyone else who comes here, the above gives an error about Boost::ut already being an alias.

This works:

```cmake
add_library(boost.ut ALIAS ut)
```

**Comment by krzysztof-jusiak** [comment]
@claremacrae would the following be okay?
* https://github.com/boost-ext/ut/pull/433

**Comment by claremacrae** [comment]
> @claremacrae would the following be okay?
> 
> * #433

Thanks! I've answered in that ticket...

I worked around the issue before you kindly added that, but I think it's likely that the change will affect others as well.

Also for others here, the suggestion in https://github.com/boost-ext/ut/issues/430#issuecomment-788043550 didn't work for me with clang9, with the latest boost.ut. I still got lots of warnings about C99 code...

This is what I needed, to work with Clang 9 on Linux:

```cmake
message(NOTICE "Fetching boost.ut...")
set(BUILD_BENCHMARKS OFF CACHE BOOL "")
set(BUILD_EXAMPLES OFF CACHE BOOL "")
set(BUILD_TESTS OFF CACHE BOOL "")
FetchContent_Declare(boost.ut
        GIT_REPOSITORY https://github.com/boost-ext/ut.git
        GIT_TAG ${UtVersion})
FetchContent_MakeAvailable(boost.ut)

if(TARGET Boost::ut)
    add_library(boost.ut ALIAS ut)
endif()

if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
    # Turn off some checks off for boost.ut
    target_compile_options(ut INTERFACE
            -Wno-c99-extensions # Needed for Boost.ut, at least in v1.1.6
            -Wno-documentation-unknown-command # unknown command tag name \userguide
            -Wno-weak-vtables
            -Wno-comma # See https://github.com/boost-ext/ut/issues/398
            )
endif()
```

**Comment by claremacrae** [comment]
Closing, since based on the comments, it seems unlikely that it's worth leaving open...

I've added notes above, in the hope of helping others out....
