### ISSUE TITLE
Should Boost be lower case?

### ISSUE THREAD

**Issue by Sebanisu** [boost-ext/ut#431]
https://github.com/boost-ext/ut/blob/1cc75c234d4005031cee581102a4a6c8b680df0a/CMakeLists.txt#L138

I linked to master branch and noticed my target_link_libraries was linked to boost::ut. Now it needs to be Boost::ut.

**Comment by Sebanisu** [comment]
```cmake
enable_testing()
include(FetchContent)
FetchContent_Declare(
        ut
        GIT_REPOSITORY https://github.com/boost-ext/ut.git
        GIT_TAG        origin/master
)
FetchContent_MakeAvailable(ut)
```
This is how i'm linking to the master branch in my project. I was just trying it out as the latest version is a little older.

**Comment by ClausKlein** [comment]
see  https://github.com/boost-ext/ut/issues/430#issuecomment-788024849

**Comment by Sebanisu** [comment]
Okay thanks
