### ISSUE TITLE
How to explicitly run the suite/registry?

### ISSUE THREAD

**Issue by WojciechMigda** [boost-ext/ut#440]
I am testing some code which internally uses `spdlog`. It turns out that `spdlog` has this thing called `registry` that is being destroyed upon program's exit.
As execution of `boost::ut` tests also occurs when its `runner` is being destroyed it happen that the tested code will execute once spdlog has finished its shutdown and cleanup, leading to attempts to use released resources.

I would find it very useful to be able to explicitly invoke testcases and suites registered with `boost::ut` `runner`. Is there maybe an existing API that I could use? If not, is it possible to have such functionality implemented?

**Comment by WojciechMigda** [comment]
I have found that I can do this:

```c++
auto ok = cfg<boost::ut::override>.run();
```
in my `main()` function.
Although it seems to do what I want, it would be nice to confirm it is not a wild hackery noone should attempt in their sane mind.

**Comment by krzysztof-jusiak** [comment]
Thanks, @WojciechMigda  for the question.

Yeah, an explicit `run` call is the way to go.
* https://github.com/boost-ext/ut/blob/master/example/run_report.cpp
