### ISSUE TITLE
Per-comparison epsilon values

### ISSUE THREAD

**Issue by tambry** [boost-ext/ut#451]
While ut supports an epsilon value from within a type this isn't flexible enough when testing math code that might require different epsilon values for operations. It may be cumbersome to have separate types with an epsilon variable or compile-time epsilon values at all.

The current way to accomplish this is:
```
using ut_value = ut::detail::value<double>;
ut::expect(ut::eq(my_math_operation(6.3), ut_value{3.0, 1.0e-5}));
```

It'd be best if one didn't have to touch the internals for this.  
Maybe something like: `ut::eq(a, b, epsilon)`

**Comment by 80Ltrumpet** [comment]
Your example can now be accomplished like this:
```c++
ut::expect(ut::near(my_math_operation(6.3), 3.0, 1e-5));
```

**Comment by tambry** [comment]
Thank you! I've converted all my code to use `ut::near()`.
