### ISSUE TITLE
Conan version 1.1.8 is broken on newer msvc.

### ISSUE THREAD

**Issue by Sebanisu** [boost-ext/ut#490]
I don't think Conan will push out a version with out a new numbered release. Since 1.1.8 is from Aug 2020. I was wondering if you could push out a new build using the current version of the code. So that Conan could release it. 

We needed a way to turn Modules off. And it only exists in the current code it doesn't exist in the current released build.

**Comment by krzysztof-jusiak** [comment]
Sure, what about tagging an new version 1.1.9? would that work?

**Comment by Sebanisu** [comment]
I think that should work. Then I just need to open an issue over there for someone to add the new version.

**Comment by krzysztof-jusiak** [comment]
Done - https://github.com/boost-ext/ut/releases/tag/v1.1.9

**Comment by Sebanisu** [comment]
https://github.com/conan-io/conan-center-index/pull/9723 looks like we're just waiting on this pull request to be reviewed. Looks like it's good otherwise. :)

**Comment by jwillikers** [comment]
Merged!

**Comment by Sebanisu** [comment]
The new version is on Conan now. So I'll go ahead and close this. Thanks everyone.

**Comment by krzysztof-jusiak** [comment]
awesome, thank you! :clap:
