### ISSUE TITLE
Strange behaviour causing the application to exit with and error

### ISSUE THREAD

**Issue by NelsonEloi** [boost-ext/ut#497]
## Expected Behavior
Expected a clean exit

## Actual Behavior
Exiting with code -1073741819.

## Steps to Reproduce the Problem

  1. Compiling and executing the attached example should cause the issue

## Specifications

  - Version: Visual Studio 202 - Version 17.2.0 Preview 1.0
  - Platform: x64
  - Subsystem:  Windows10
[Prog.zip](https://github.com/boost-ext/ut/files/8260256/Prog.zip)

Thank you for a clean testing framework

**Comment by NelsonEloi** [comment]
Adding some extra info,

I think this happens because I'm using a global variable in the test, function/class statics would be the same.
Because the runner executes during the destruction phase, by the time it runs, globals/statics might have already been destroyed.

The obvious solutions, is don't test globals/statics, but then you can't test a pretty common pattern of a Singleton.

Thank you

**Comment by krzysztof-jusiak** [comment]
oh I see,

In that case, can you try with, to avoid the issue
```
int main() {
  return ut::cfg<>.run();  // explicitly run registered test suites
}
```

* https://github.com/boost-ext/ut/blob/master/example/run.cpp

**Comment by NelsonEloi** [comment]
Yeah, that solved the issue.

You might want to add a note regarding this for future reference

Thank you very much
