### ISSUE TITLE
Print type name in failed templated test

### ISSUE THREAD

**Issue by jessestricker** [boost-ext/ut#500]
It would be really nice if a failing template test prints the type name for which it failed.

So for this code,
```
"test"_test = []<class T>{
  expect(std::same_as<bool, T>);
} | std::tuple<bool, int>{};
```

_ut_ should print something like
```
Running "test<bool>"...PASSED
Running "test<int>"...
  test.cpp:2:FAILED [false]
FAILED
```

**Comment by krzysztof-jusiak** [comment]
What about using type<X> == type<Y> instead?

```
int main() {
  using namespace boost::ut;

  "test"_test = []<class T>{
    expect(type<T> == type<bool>);
  } | std::tuple<bool, int>{};
}
```

```
Running "test"...PASSED
Running "test"...
  <source>:8:FAILED [int == bool]
FAILED
```

https://godbolt.org/z/8hsYbx546

**Comment by jessestricker** [comment]
I have to admit that my example was simplified a bit.

My actual use case is something like:
```cpp
"test"_test = []<class T>{
  expect(std::is_signed_v<T::primitive>);
} | std::tuple<custom_signed_int_wrappers...>;
```
Here I want to test for some signed int wrapper types (like foonathan's type_safe),
their underlying types are indeed signed types built into the C++ language.

If the above fails for just some of the tuple element types, I can't know from the log output which one.
I guess you could add some manual logging into the test case, but maybe _ut_ should provide that on its own
for convenience? Other test frameworks also do that (doctest and Catch are the ones I know of).

**Comment by krzysztof-jusiak** [comment]
What about
```
int main() {
  using namespace boost::ut;

  "test"_test = []<class T>{
    expect(std::is_signed_v<T>) << reflection::type_name<T>();
  } | std::tuple<bool, int>{};
}
```

https://godbolt.org/z/7jhd3q9zs

**Comment by jessestricker** [comment]
Yes, that looks great! I did not find something like that in the documentation however.
Maybe just the docs need an update then?

**Comment by jessestricker** [comment]
Do you want me to open a PR with some documentation improvements regarding this?

**Comment by krzysztof-jusiak** [comment]
oh that would be awesome, thank you :pray:
