### ISSUE TITLE
No way to test strings nicely

### ISSUE THREAD

**Issue by cooldome** [boost-ext/ut#561]
ut:expect(a == "asba") doesn't produce nice error message, no suffix to create ut::TExpr for strings

## Suggestion:

introduce suffix for strings, but "_s" is already taken, so it can be either "_str" or "_sv" for string_view.

ut:expect(a == "asba"_str)
ut:expect(a == "asba"_sv)

**Comment by cooldome** [comment]
found a way to make it work

**Comment by Life4gal** [comment]
> found a way to make it work

Would you mind explaining how you got it to work? :)
