### ISSUE TITLE
Test class should own its name if constructed with std::string

### ISSUE THREAD

**Issue by R2RT** [boost-ext/ut#569]
## Expected Behavior

Test passes

## Actual Behavior

Test runner crashes due to accessing deallocated string or reports corrupted names:

`""runner returned from test w/o signaling: not popping because 'ÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝ' differs from '\0ÍÍÍÍÍÍÍÍÍÍÍ'\n"`

or 

`Running test "▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌"... FAILED`

## Steps to Reproduce the Problem
Run parametrized test example from readme.

```c++
int main() {
  for (auto i : std::vector{1, 2, 3}) {
    test("parameterized " + std::to_string(i)) = [i] { // 3 tests
      expect(that % i > 0); // 3 asserts
    };
  }
}
```

## Specifications

  - Version: master
  - Platform: MSVC v143
  - Subsystem: runner

---

Changing
```diff
 struct test {
   std::string_view type{};
-  std::string_view name{};
+  std::string name{};
   std::vector<std::string_view> tag{};
```
Fixes this issue

**Comment by SuperFola** [comment]
I also have this problem on master. The ugly workaround is to create a string and make a string_view on top, it would be nice to fix it upstream.

workaround:
```cpp
std::string test_name = "output the same error message (" + stem + ")";
should(std::string_view(test_name)) = [&] {
    expect(that % ss.str() == Ark::Utils::readFile(expected_path.string()));
};
```
