### ISSUE TITLE
Is it possible to have `named` suites

### ISSUE THREAD

**Issue by multivac61** [boost-ext/ut#585]
Here is an example of a `suite` called `my_named_suite`: [godbolt](https://godbolt.org/z/ErvhrqKMo).

The output is currently
```
ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 0
Suite '**unnamed suite**': all tests passed (2 asserts in 3 tests)
Suite 'global': all tests passed (0 asserts in 0 tests)
```

Would it be possible to get the name of the suite in the output?

**Comment by krzysztof-jusiak** [comment]
To do so explicit name on the suite has to be added as C++ doesn't have reflection to get the actual name of an object.

```
suite<"name">
```

https://godbolt.org/z/v7b5sdaeM

**Comment by multivac61** [comment]
Thank you Kris!
